Iter5
Bloodlog/metrics pull request #5
Opened 2024-11-30 19:45 UTC by Bloodlog

2024-12-03 17:07 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-12-03 17:07 UTC, s-shpak commented on .DS_Store
Этот файл не надо пушить в репозиторий

2024-12-03 17:07 UTC, s-shpak commented on cmd/agent/main.go
> +		return err
Ошибки из сторонних пакетов надо оборачивать при помощи `fmt.Errorf` и `%w`. Здесь смотри подробнее как: https://go.dev/blog/go1.13-errors#wrapping-errors-with-w

2024-12-03 17:07 UTC, s-shpak commented on internal/.DS_Store
Аналогично

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/config/config.go
> +	parts := strings.Split(*address, ":")
Я бы не парсил строку с адресом сервера, а запускал ее ровно так, как она передана пользователем. Если пользователь ошибся, то отправить запрос просто не получится. Но если ты все же решишь парсить строку, то я рекомендую использовать `https://pkg.go.dev/net/url#Parse`

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/config/config.go
> +		os.Exit(1)
`os.Exit(1)` завершит процесс с кодом 1 (ненулевой код = ошибка). Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса.

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/config/config.go
> +		_, _ = fmt.Fprintf(os.Stderr, "Error: unknown flags detected")
Не используй пакет `fmt`, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/config/config.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +	go func() {
Я не буду пока комментировать недочеты связанные с работой с горутинами. Вернемся к ним в четвертом спринте. Этот комментарий можно зарезолвить

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +			stringMetrics = append(stringMetrics, fmt.Sprintf("%s:%d", metric.Name, metric.Value))
Неэффективная передача здесь: почему бы передавать слайс структур, в которых будут лежать имя и значение метрики ?

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +		time.Sleep(time.Duration(pollInterval) * time.Second)
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +		err := service.SendIncrement(client, uint64(counter), debug)
Считать необходимо не количество отправлений метрик, а количество их сборов

2024-12-03 17:07 UTC, s-shpak commented on internal/agent/repository/repository.go
> +	mu sync.RWMutex
1. Правильно хранить указатель на мьютекс, а не сам мьютекс -- мьютекс нельзя копировать после инициализации. Почему это так мы, возмжно, разберем во второй части курса, пока это правило лучше просто запомнить
2. Хорошо, что ты знаешь о существовании `RWMutex`, но в в данном случае лучше использовать обычный, т.к. с `RWMutex` твое приложение, скорее всего, будет работать медленее. `RWMutex` можно исползовать если количество записей на порядки превышает количество чтений, и его воздействие на быстродействие приложения стоит проверять при помощи бенчмаркинга
3. А зачем этот мьютекс ? Доступ к чему он защищает ?

2024-12-03 17:07 UTC, s-shpak commented on internal/server/handlers/counter/get_test.go
> +	memStorage := repository.NewMemStorage()
Я советую тебе создавать все необходимые сущности в каждом отдельном тесте. Они создаются очень быстро и не требуют большого количества вычислительных ресурсов. При этом их пересоздание в каждом тесте гарантирует, что тесты будут выполняться изолировано и не будут влиять на выполнение других тестов.

2024-12-03 17:07 UTC, s-shpak commented on internal/server/handlers/gauge/get.go
> +			response.WriteHeader(http.StatusInternalServerError)
Ошибки 5** нужно логировать для дальнейшего их исправления

2024-12-03 17:07 UTC, s-shpak commented on internal/server/handlers/gauge/get.go
> +		_, writeErr := response.Write([]byte(strconv.FormatFloat(gauge, 'g', -1, 64)))
Зачем здесь объявлять новую переменную `writeErr` ?

2024-12-03 17:07 UTC, s-shpak commented on internal/server/handlers/list.go
> +		_, err := response.Write([]byte("<html><head><title>Metrics List</title></head><body><h1>Metrics</h1><ul>"))
Для работы с `HTML` документами лучше использовать пакет html/template: https://pkg.go.dev/html/template

2024-12-06 21:04 UTC, Bloodlog commented on internal/server/handlers/list.go
> +		_, err := response.Write([]byte("<html><head><title>Metrics List</title></head><body><h1>Metrics</h1><ul>"))
Добавил пакет html/template и заменил

2024-12-06 21:04 UTC, Bloodlog commented on internal/server/handlers/gauge/get.go
> +		_, writeErr := response.Write([]byte(strconv.FormatFloat(gauge, 'g', -1, 64)))
Исправил

2024-12-06 21:04 UTC, Bloodlog commented on internal/server/handlers/counter/get_test.go
> +	memStorage := repository.NewMemStorage()
Исправил

2024-12-06 21:05 UTC, Bloodlog commented on internal/agent/repository/repository.go
> +	mu sync.RWMutex
Удалил мютекс у этого репозитория

2024-12-06 21:05 UTC, Bloodlog commented on internal/agent/config/config.go
> +		os.Exit(1)
Исправил

2024-12-06 21:05 UTC, Bloodlog commented on internal/agent/config/config.go
> +	parts := strings.Split(*address, ":")
Добавил пакет и исправил

2024-12-06 21:05 UTC, Bloodlog commented on internal/.DS_Store
Исправил

2024-12-06 21:06 UTC, Bloodlog commented on cmd/agent/main.go
> +		return err
Исправил

2024-12-06 21:06 UTC, Bloodlog commented on .DS_Store
Удалил

2024-12-06 21:07 UTC, Bloodlog commented on internal/agent/config/config.go
> +	if envRunAddr := os.Getenv("ADDRESS"); envRunAddr != "" {
Исправил

2024-12-06 21:07 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +	go func() {
Удалил

2024-12-06 21:07 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +			stringMetrics = append(stringMetrics, fmt.Sprintf("%s:%d", metric.Name, metric.Value))
Удалил

2024-12-06 21:08 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +		time.Sleep(time.Duration(pollInterval) * time.Second)
Заменил на Tikcer

2024-12-06 21:08 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +		err := service.SendIncrement(client, uint64(counter), debug)
Перенес счетчик на получение метрик

2024-12-06 21:09 UTC, Bloodlog commented on internal/server/handlers/gauge/get.go
> +			response.WriteHeader(http.StatusInternalServerError)
Добавил лог log.Printf("error writing response: %v", err) чуть выше

2024-12-06 21:58 UTC, Bloodlog commented on internal/agent/config/config.go
> +		_, _ = fmt.Fprintf(os.Stderr, "Error: unknown flags detected")
Добавил лог и создал ошибки
	ErrParseAddress   = errors.New("failed to parse address (expected host:port)")
	ErrArgumentsCount = errors.New("unknown flags or arguments detected")

2024-12-08 22:16 UTC, s-shpak requested changes

2024-12-08 22:16 UTC, s-shpak commented on internal/agent/config/config.go
> +	ErrParseAddress   = errors.New("failed to parse address (expected host:port)")
Ошибки стоит объявлять в виде глобальных эксопртируемых переменных только тогда, когда они являются частью интерфейса, предоставляемого пакетом: т.е. другой пакет, который его использует будет иметь информацию о том, что какая-то функция может вернуть эти экспортируемую ошибку.

В данном случае это не так: эта ошибка нигде больше не используется -- другие пакеты не используют ее при вызове функций `errors.Is`/`errors.As`. пПотому нет смысла объявлять ее в качестве глобальной переменной. 

Это относится и к другим подобным ошибкам.

2024-12-08 22:16 UTC, s-shpak commented on internal/agent/config/config.go
> +		log.Printf("Warning: invalid value for %s, using default: %d", envKey, defaultValue)
Fallback на дефолтные значения чаще стреляет в ногу, чем помогает. Представь себе, что ты запускаешь сервис с некорректной конфигурацией, и он сразу падает. Ты правишь конфигурацию, далее сервис работает корректно.

Теперь представь, что ты запускаешь сервис, и он запускается, но при инициализации компонентов происходит fallback на дефолтное значение, потому что заданное тобой некорректно. Тогда ты будешь думать, что сервис проиницализирован одним образом, а он будет работать по-другому и неожиданно для тебя.

https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so

2024-12-08 22:16 UTC, s-shpak commented on internal/agent/service/gauge.go
> +		log.Printf("failed to send POST request PollCount: %v", err)
Ошибки стоит (как правило) логировать в момент, когда они обрабатываются: т.е. когда ошибка возвращена на тот слой, где она может быть обработана, а не прокинута выше.

2024-12-08 22:16 UTC, s-shpak commented on internal/agent/service/gauge.go
> +		return ErrSendMetric
В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где. Сжедать это можно при помощи `fmt.Errorf` и `%w`

2024-12-08 22:16 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +			counter++
Сейчас это работает некорректно: счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-12-08 22:16 UTC, s-shpak commented on internal/server/handlers/list_test.go
> +			counterMatch, _ := regexp.MatchString(counterValueStr, respBody)
Ошибки нужно проверять всегда (в том числе в тестах), кроме очень редких случаев, когда ошибку можно явным образом проигнорировать. Это не тот случай.

2024-12-08 22:16 UTC, s-shpak commented on internal/server/handlers/list_test.go
> +				t.Fatalf("response body is empty")
Вызов Fatal из `t.Run` приведет к панике в тесте. Паниковать не надо, потому используй `t.Error` + `return`

2024-12-08 22:16 UTC, s-shpak commented on internal/server/repository/repository.go
> +	mu       *sync.RWMutex
См. предыдущий комментарий про `RWMutex`

2024-12-08 22:16 UTC, s-shpak commented on internal/server/repository/repository.go
> +	return ms.gauges
Сейчас мьютекс по сути ничего не защищает в этой и следующей функциях: мапы копируются не глубоко, а значит, что после Unlock'а мьютекса будет существовать еще одна копия той же мапы. При конкурентном обращении к ней и к оригиналу, произойдет data race

2024-12-09 13:30 UTC, Bloodlog commented on internal/server/repository/repository.go
> +	return ms.gauges
Удалил

2024-12-09 13:30 UTC, Bloodlog commented on internal/server/repository/repository.go
> +	mu       *sync.RWMutex
Удалил пока что RWMutex

2024-12-09 13:31 UTC, Bloodlog commented on internal/server/handlers/list_test.go
> +				t.Fatalf("response body is empty")
Заменил на t.Error

2024-12-09 13:31 UTC, Bloodlog commented on internal/server/handlers/list_test.go
> +			counterMatch, _ := regexp.MatchString(counterValueStr, respBody)
Добавил проверку на ошибки

2024-12-09 13:31 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +			counter++
Исправил счетчик

2024-12-09 13:32 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +			counter++
1 Агент - Собираю метрики, инкрементирую счетчик, как только отправляется счетчик - он сбрасывается.
2 Сервер - Счетчик прибавляется к предыдущему значению в репозитории сервера.

2024-12-09 13:32 UTC, Bloodlog commented on internal/agent/service/gauge.go
> +		return ErrSendMetric
Обернул в fmt.Errorf

2024-12-09 13:32 UTC, Bloodlog commented on internal/agent/service/gauge.go
> +		log.Printf("failed to send POST request PollCount: %v", err)
Вынес логирование выше

2024-12-09 13:33 UTC, Bloodlog commented on internal/agent/config/config.go
> +		log.Printf("Warning: invalid value for %s, using default: %d", envKey, defaultValue)
Изменил логику поведения

2024-12-09 13:33 UTC, Bloodlog commented on internal/agent/config/config.go
> +	ErrParseAddress   = errors.New("failed to parse address (expected host:port)")
Удалил глобальные ошибки

2024-12-09 21:29 UTC, s-shpak requested changes

2024-12-09 21:29 UTC, s-shpak commented on internal/server/repository/repository.go
> +	return ms.gauges
Я бы скорее посоветовал тебе копировать значения, и возвращать глубокую копию. Мьютекс лучше оставить

2024-12-10 05:37 UTC, Bloodlog commented on internal/server/repository/repository.go
> +	return ms.gauges
Вернул мутекс и добавил глубокое копирование мап

2024-12-10 12:56 UTC, s-shpak approved these changes

2024-12-11 05:09 UTC, merged