Iter9
Bloodlog/metrics pull request #9
Opened 2024-12-17 21:25 UTC by Bloodlog

2024-12-23 01:44 UTC, s-shpak requested changes

2024-12-23 01:44 UTC, s-shpak commented on cmd/agent/main.go
> +var sugar zap.SugaredLogger
Я не советую использовать глобальный логгер. Такая практика встречается, но я предлагаю не использовать ее в курсе.

Единственный аргумент для использования глобального логгера -- возможность не передавать его напрямую в компоненты, где он используется. При этом использование глобального логгера несет в себе все минусы глобальных переменных, а также минусы самого глобального логгера.

Можно выделить две основные проблемы "глобального" подхода: 

1. Теперь ты не можешь кастомизировать логгер для конкретного компонента, в котором он используется. Например, если логгер явным образом передается в компонент при его инициализации, то ты можешь настроить его так, чтобы к каждому сообщению добавлялось поле с именем компонента, который это сообщение сгенерировал. Вобщем, локальные логгеры кастомизируются легко, глобальные -- сложно.

2. С одной стороны, удобно, что логгер не надо явным образом передавать в компонент. С другой, теперь мы создаем неявные зависимости: поведение компонента зависит от логгера (если, например, логгер не будет корректно проинициализирован, то компонент тоже поломается, т.к. при вызове логгера будет падать). Неявные зависимости хуже чем явные. Потому с моей т.з. передавать логгер явным образом как аргумент функции, или как поле объекта -- лучше, чем спрятать его в глобальную переменную

2024-12-23 01:44 UTC, s-shpak commented on internal/server/repository/file.go
> +	Storage  MetricStorage
Кажется, что эти поля не надо экспортировать

2024-12-23 01:44 UTC, s-shpak commented on internal/server/repository/file.go
> +			fmt.Printf("Error saving metrics: %v\n", err)
После добавления логгера в проект `fmt.Print`/`fmt.Println`/`fmt.Printf` использовать нельзя

2024-12-23 01:44 UTC, s-shpak commented on cmd/server/main.go
> +	fileStorage := repository.NewFileStorageWrapper(storage, configs.FileStoragePath, configs.StoreInterval)
Тебе нужно поддерживать возможность запуска сервиса ьзе записи в файл, т.е. тебе надо проверить, что `FileStoragePath` был сконфигурирован при запуске сервиса

2024-12-23 01:44 UTC, s-shpak commented on cmd/server/metrics.json
Этот файл не надо класть в репозиторий

2024-12-23 01:44 UTC, s-shpak commented on internal/agent/config/config.go
> +		logger.Infoln(err.Error(), nameError, "read flag pool interval")
Ошибку нужно прокидывать как можно дальге наверх, и логировать их на последжнем уровен, когда ошибка не может быть передана дальше. Воспринимай логирование как обработку ошибки

2024-12-23 01:44 UTC, s-shpak commented on internal/agent/handlers/agent.go
> +	DefaultNameCounter = "PollCount"
Эти константы должны экспортироваться?

2024-12-23 01:44 UTC, s-shpak commented on internal/server/handlers/web/get.go
> +			logger.Infow("error in service", nameError, err)
Штатные ошибки не надо логировать

2024-12-23 01:44 UTC, s-shpak commented on internal/server/middleware/compression.go
> +	HeaderDefaultEncoding = "Content-Encoding"
Неправильно имя константы

2024-12-23 01:44 UTC, s-shpak commented on internal/server/repository/file_test.go
> +		t.Fatalf("SaveToFile failed: %v", err)
Лучше использовать здесь `t.Error` + `return`: `t.Fatal` приводит к панике при параллельном запуске нескольких тест-кейсов; так что если этот тест изменится, это приведет к проблеме. К тому же `t.Fatal` лучше заменить на `t.Error` для единообразия

2024-12-25 20:25 UTC, Bloodlog commented on cmd/agent/main.go
> +var sugar zap.SugaredLogger
Исправил

2024-12-25 20:25 UTC, Bloodlog commented on cmd/agent/main.go
> +var sugar zap.SugaredLogger
Пока не очень разобрался с кастомизированием логгера, надеюсь чуть позже пойму и отрефакторю

2024-12-25 20:26 UTC, Bloodlog commented on internal/server/repository/file.go
> +	Storage  MetricStorage
Исправил

2024-12-25 20:26 UTC, Bloodlog commented on internal/server/repository/file.go
> +			fmt.Printf("Error saving metrics: %v\n", err)
Исправил

2024-12-25 20:27 UTC, Bloodlog commented on cmd/server/main.go
> +	fileStorage := repository.NewFileStorageWrapper(storage, configs.FileStoragePath, configs.StoreInterval)
Исправил
Сделал проверку if fileStoragePath != ""  дя проверки на был ли сконфигурирован при запуске сервиса.
Надеюсь верно понял

2024-12-25 20:27 UTC, Bloodlog commented on cmd/server/metrics.json
Исправил, не заметил

2024-12-25 20:28 UTC, Bloodlog commented on internal/agent/handlers/agent.go
> +	DefaultNameCounter = "PollCount"
Исправил

2024-12-25 20:28 UTC, Bloodlog commented on internal/server/handlers/web/get.go
> +			logger.Infow("error in service", nameError, err)
Исправил

2024-12-25 20:28 UTC, Bloodlog commented on internal/server/middleware/compression.go
> +	HeaderDefaultEncoding = "Content-Encoding"
Исправил, не заметил

2024-12-25 20:28 UTC, Bloodlog commented on internal/server/repository/file_test.go
> +		t.Fatalf("SaveToFile failed: %v", err)
Исправил

2024-12-25 20:35 UTC, Bloodlog commented on internal/agent/config/config.go
> +		logger.Infoln(err.Error(), nameError, "read flag pool interval")
Удалил логгер из конфига

2024-12-27 15:48 UTC, s-shpak requested changes

2024-12-27 15:48 UTC, s-shpak commented on internal/agent/handlers/agent.go
>  				return fmt.Errorf("failed to send Increment %d to server: %w", counter, err)
Если ошибка возвращается выше, то в общем случае нет смысла ее логировать там же: можно будет залогировать ее там, где она будет обрабатываться

2024-12-27 15:48 UTC, s-shpak commented on internal/agent/repository/repository.go
> +	metrics[27] = Metric{"RandomValue", rand.Uint64()}
Извини, пожалуйста, я почему-то не обратил на это внимание. Лучше так:

```go
metrics := make([]Metric, 0)
metrics = append(metrics, Metric{...})
...
```

2024-12-27 15:48 UTC, s-shpak commented on cmd/agent/main.go
> +var sugar zap.SugaredLogger
С zap все довольно просто: когда ты передаешь логгер в новый компонент, то ты можешь добавить контекст в него при помощи https://pkg.go.dev/go.uber.org/zap#Logger.With. Это позволит, например, автоматически логировать имя компонента, который логирует событие

2024-12-27 19:00 UTC, Bloodlog commented on internal/agent/repository/repository.go
> +	metrics[27] = Metric{"RandomValue", rand.Uint64()}
Если сделать так, то линтер ругается:
```
{
  "Issues": [
    {
      "FromLinter": "gocritic",
      "Text": "appendCombine: can combine chain of 28 appends into one",
      "Severity": "error",
      "SourceLines": [
        "\tmetrics = append(metrics, Metric{\"Alloc\", memStats.Alloc})"
      ],
      "Replacement": null,
      "Pos": {
        "Filename": "internal/agent/repository/repository.go",
        "Offset": 344,
        "Line": 26,
        "Column": 2
      },
      "ExpectNoLint": false,
      "ExpectedNoLintLinter": ""
    }
  ],
```

Исправил на вариант:
```

	metrics := append([]Metric{},
		Metric{"Alloc", memStats.Alloc},
		Metric{"BuckHashSys", memStats.BuckHashSys},
		Metric{"Frees", memStats.Frees},
		Metric{"GCCPUFraction", uint64(memStats.GCCPUFraction)},
...
```

2025-01-04 15:24 UTC, Bloodlog commented on internal/agent/handlers/agent.go
>  				return fmt.Errorf("failed to send Increment %d to server: %w", counter, err)
Исправил

2025-01-04 15:25 UTC, Bloodlog commented on cmd/agent/main.go
> +var sugar zap.SugaredLogger
Добавил logger.With

2025-01-06 09:46 UTC, s-shpak approved these changes

2025-01-06 14:12 UTC, merged